name: "Build: Image"

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerfile_path:
        type: string
        default: "./Dockerfile"
      build_context:
        type: string
        default: "."
      build_args:
        type: string
        default: ""
      runs_on:
        type: string
        default: "ubuntu-latest"
    outputs:
      image_tag:
        description: "Image tag (git SHA)"
        value: ${{ jobs.build.outputs.image_tag }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: false
          load: true
          tags: ${{ inputs.app_name }}:${{ github.sha }}
          build-args: ${{ inputs.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

